name: Static Code Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Static Code Analysis with PMD
        uses: pmd/pmd-github-action@v1
        with:
          rulesets: 'java-basic'

      - name: Fail build if there are violations
        if: steps.pmd.outputs.violations != 0
        run: exit 1
